// GENERATED by etl/download_player_photos.py -- do not edit by hand.
//
// One portrait per top-100 player. Each Wikidata entity was matched to our
// own player row by date of birth before its photo was accepted, and every
// crop is centred on a Vision-detected face. Players with no freely licensed
// photograph on Commons are absent here and fall back to a monogram.

export type PlayerPhoto = {
  src: string;
  credit: string | null;
  license: string | null;
  source: string | null;
};

export const PLAYER_PHOTOS: Record<number, PlayerPhoto> = {
  100644: { src: "/players/100644.jpg", credit: "Keith Allison from Hanover, MD, USA", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Alexander_Zverev_(30004409818).jpg" }, // Alexander Zverev
  104925: { src: "/players/104925.jpg", credit: "Andymiah", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Novak_Djokovic_Paris_2024_Olympic_Games_(cropped).jpg" }, // Novak Djokovic
  105173: { src: "/players/105173.jpg", credit: "Carine06 from UK", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Adrian_Mannarino_in_sepia_(14444726508).jpg" }, // Adrian Mannarino
  105227: { src: "/players/105227.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Cilic_US16_(66)_(29569801430).jpg" }, // Marin Cilic
  105477: { src: "/players/105477.jpg", credit: "Carine06", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Marco_Trungelliti.jpg" }, // Marco Trungelliti
  105526: { src: "/players/105526.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Struff_RG18_(6)_(42260262224).jpg" }, // Jan Lennard Struff
  105807: { src: "/players/105807.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Carreno_Busta_RG19_(11)_(48199369451).jpg" }, // Pablo Carreno Busta
  105870: { src: "/players/105870.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Hanfmann_RGQ19_(23)_(48002696768).jpg" }, // Yannick Hanfmann
  105902: { src: "/players/105902.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Duckworth_WMQ14_(3)_(14420344920).jpg" }, // James Duckworth
  105916: { src: "/players/105916.jpg", credit: "Diliff", license: "CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:M%C3%A1rton_Fucsovics_3,_2015_Wimbledon_Qualifying_-_Diliff.jpg" }, // Marton Fucsovics
  106218: { src: "/players/106218.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Giron_RG22_(4)_(52144109873).jpg" }, // Marcos Giron
  106421: { src: "/players/106421.jpg", credit: "LacosteWiki", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Danill_Medvedev_Miami_2019_(cropped).jpg" }, // Daniil Medvedev
  111460: { src: "/players/111460.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Halys_RG15_(22)_(18685208034).jpg" }, // Quentin Halys
  111575: { src: "/players/111575.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Khachanov_WMQ15_(11)_(19944440142).jpg" }, // Karen Khachanov
  111794: { src: "/players/111794.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Majchrzak_RG21_(2)_(51376823294).jpg" }, // Kamil Majchrzak
  111815: { src: "/players/111815.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Norrie_WM17_(2)_(36143094896).jpg" }, // Cameron Norrie
  122298: { src: "/players/122298.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Van_de_Zandschulp_RG21_(29)_(51375315497).jpg" }, // Botic Van De Zandschulp
  122330: { src: "/players/122330.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Sascha_Bublik_(2023_DC_Open)_05_(cropped).jpg" }, // Alexander Bublik
  124187: { src: "/players/124187.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Opelka_WMQ18_(7)_(42834211754).jpg" }, // Reilly Opelka
  126094: { src: "/players/126094.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Andrey_Rublev_(2023_US_Open)_12.jpg" }, // Andrey Rublev
  126127: { src: "/players/126127.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Bonzi_RG18_(7)_(42260485824).jpg" }, // Benjamin Bonzi
  126203: { src: "/players/126203.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Fritz_RG19_(23)_(48199372707).jpg" }, // Taylor Fritz
  126205: { src: "/players/126205.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Paul_RG21_(2)_(51376841649).jpg" }, // Tommy Paul
  126207: { src: "/players/126207.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Tiafoe_EBN17_(3)_(35716381482).jpg" }, // Frances Tiafoe
  126214: { src: "/players/126214.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Tabilo_RGQ23_(52942983162).jpg" }, // Alejandro Tabilo
  126239: { src: "/players/126239.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Rinderknech_RG18_(42978781661).jpg" }, // Arthur Rinderknech
  126610: { src: "/players/126610.jpg", credit: "Presidenza della Repubblica", license: "Attribution", source: "https://commons.wikimedia.org/wiki/File:Matteo_Berrettini,_2021.jpg" }, // Matteo Berrettini
  126774: { src: "/players/126774.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Tsitsipas_S._MCM22_(20)_(52036915350).jpg" }, // Stefanos Tsitsipas
  126846: { src: "/players/126846.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Vukic_RGQ22_(5)_(52128494517).jpg" }, // Aleksandar Vukic
  127157: { src: "/players/127157.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Altmaier_RG22_(24)_(52144567090).jpg" }, // Daniel Altmaier
  128034: { src: "/players/128034.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Hurkacz_RG19_(10)_(48199235282).jpg" }, // Hubert Hurkacz
  132283: { src: "/players/132283.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Sonego_MCM22_(22)_(52035355412).jpg" }, // Lorenzo Sonego
  132686: { src: "/players/132686.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Borges_BOR22_(52082935912).jpg" }, // Nuno Borges
  133430: { src: "/players/133430.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Shapovalov_RG22_(26)_(52144052686).jpg" }, // Denis Shapovalov
  134770: { src: "/players/134770.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Ruud_MCM22_(31)_(52036646944).jpg" }, // Casper Ruud
  134868: { src: "/players/134868.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Griekspoor_RG22_(1)_(52144112028).jpg" }, // Tallon Griekspoor
  144719: { src: "/players/144719.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Munar_WM19_(12)_(48521794586).jpg" }, // Jaume Munar
  144869: { src: "/players/144869.jpg", credit: "Jmmuguerza", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Cordoba_Open_2021_13_(cropped).jpg" }, // Tomas Martin Etcheverry
  144895: { src: "/players/144895.jpg", credit: "Carine06 from UK", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Corentin_Moutet_(45135594272)_(cropped).jpg" }, // Corentin Moutet
  200000: { src: "/players/200000.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Auger_Aliassime_RG21_(91)_(51377187345).jpg" }, // Felix Auger Aliassime
  200005: { src: "/players/200005.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Humbert_RG19_(7)_(48199190756).jpg" }, // Ugo Humbert
  200116: { src: "/players/200116.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Ugo_Carabelli_RGQ22_(2)_(52129754339).jpg" }, // Camilo Ugo Carabelli
  200175: { src: "/players/200175.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Kecmanovic_RG19_(42)_(48199200981).jpg" }, // Miomir Kecmanovic
  200221: { src: "/players/200221.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Davidovich_Fokina_RG19_(9)_(48199314646).jpg" }, // Alejandro Davidovich Fokina
  200240: { src: "/players/200240.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Kopriva_BLO22_(14)_(52157049388).jpg" }, // Vit Kopriva
  200267: { src: "/players/200267.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Bergs_MLC21_(2).jpg" }, // Zizou Bergs
  200282: { src: "/players/200282.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:De_Minaur_RG19_(23)_(48199315646).jpg" }, // Alex De Minaur
  200443: { src: "/players/200443.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Adam_Walton_(2023_Cary)_03_(cropped).jpg" }, // Adam Walton
  200473: { src: "/players/200473.jpg", credit: "Skyscraper2010", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Valentin_Vacherot_Basel_2025_(cropped).jpg" }, // Valentin Vacherot
  200615: { src: "/players/200615.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Popyrin_RG19_(46)_(48199101562).jpg" }, // Alexei Popyrin
  200624: { src: "/players/200624.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Sebastian_Korda_(2023_DC_Open)_02.jpg" }, // Sebastian Korda
  202058: { src: "/players/202058.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Tirante_WMQ23_(53062069430).jpg" }, // Thiago Agustin Tirante
  202103: { src: "/players/202103.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Cerundolo_MCM23_(21)_(52883527185)_(cropped).jpg" }, // Francisco Cerundolo
  202104: { src: "/players/202104.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Baez_RG22_(6)_(52144105338).jpg" }, // Sebastian Baez
  202385: { src: "/players/202385.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Brooksby_RG21_(42)_(51376192761).jpg" }, // Jenson Brooksby
  206173: { src: "/players/206173.jpg", credit: "The White House derivative work: Kacir", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Jannik_Sinner_US_Open_2025_(cropped).jpg" }, // Jannik Sinner
  206499: { src: "/players/206499.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Aleksandar_Kovacevic_(Roland_Garros_2023)_01_(cropped).jpg" }, // Aleksandar Kovacevic
  206681: { src: "/players/206681.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Marozs%C3%A1n_WMQ23_(53062093200).jpg" }, // Fabian Marozsan
  206909: { src: "/players/206909.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Brandon_Nakashima_(2024_DC_Open)_01_(cropped).jpg" }, // Brandon Nakashima
  207182: { src: "/players/207182.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Nava_BLO22_(24)_(52157277484).jpg" }, // Emilio Nava
  207411: { src: "/players/207411.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:De_Jong_WMQ23_(53061896384).jpg" }, // Jesper De Jong
  207518: { src: "/players/207518.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Musetti_MCM22_(52)_(52036662724).jpg" }, // Lorenzo Musetti
  207678: { src: "/players/207678.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Cerundolo_JM._RGQ22_(3)_(52128606242).jpg" }, // Juan Manuel Cerundolo
  207681: { src: "/players/207681.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Francisco_Comesa%C3%B1a_(2023_US_Open)_03.jpg" }, // Francisco Comesana
  207686: { src: "/players/207686.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Alexander_Shevchenko_(2023_DC_Open)_01_(cropped).jpg" }, // Alexander Shevchenko
  207830: { src: "/players/207830.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Machac_MLC22.jpg" }, // Tomas Machac
  207925: { src: "/players/207925.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Cobolli_WMQ23_(53061712891).jpg" }, // Flavio Cobolli
  207989: { src: "/players/207989.jpg", credit: "Like tears in rain derivative work: Kacir", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Carlos_Alcaraz_Roland_Garros_2025_(cropped).jpg" }, // Carlos Alcaraz
  208029: { src: "/players/208029.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Rune_RG22_(4)_(52144534990).jpg" }, // Holger Rune
  208103: { src: "/players/208103.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Lehecka_MCM22_(44)_(52035368427).jpg" }, // Jiri Lehecka
  208118: { src: "/players/208118.jpg", credit: "Hameltion derivative work: Kacir", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Eliot_Spizzirri_(2023_Cary)_04_(cropped).jpg" }, // Eliot Spizzirri
  208233: { src: "/players/208233.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Mattia_Bellucci_(2024_DC_Open)_02_(cropped).jpg" }, // Mattia Bellucci
  208260: { src: "/players/208260.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Svajda_RGQ23.jpg" }, // Zachary Svajda
  208286: { src: "/players/208286.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Arnaldi_BLO22_(68)_(52157038811).jpg" }, // Matteo Arnaldi
  208316: { src: "/players/208316.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Royer_MLC22.jpg" }, // Valentin Royer
  208363: { src: "/players/208363.jpg", credit: "BugWarp", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Road_2_Australia_-_Navone_V_Burruchaga_Final_-_BugWarp_206_(cropped).jpg" }, // Mariano Navone
  208659: { src: "/players/208659.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Giovanni_Mpetshi_Perricard_(2023_US_Open)_01_(cropped).jpg" }, // Giovanni Mpetshi Perricard
  208882: { src: "/players/208882.jpg", credit: "BugWarp derivative work: Kacir", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Rom%C3%A1n_Andr%C3%A9s_Burruchaga_Road_2_Australia_2025_(cropped).jpg" }, // Roman Andres Burruchaga
  209070: { src: "/players/209070.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Cazaux_BOR22_(52082936542).jpg" }, // Arthur Cazaux
  209098: { src: "/players/209098.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Medjedovic_RGQ23.jpg" }, // Hamad Medjedovic
  209113: { src: "/players/209113.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Diallo_WMQ23_(53061896439).jpg" }, // Gabriel Diallo
  209226: { src: "/players/209226.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Daniel_Vallejo_(2023_Cary)_03.jpg" }, // Adolfo Daniel Vallejo
  209260: { src: "/players/209260.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Darderi_WMQ23_(53062101185).jpg" }, // Luciano Darderi
  209279: { src: "/players/209279.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Atmane_RGQ23_(52944022580).jpg" }, // Terence Atmane
  209414: { src: "/players/209414.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Van_Assche_RGQ22_(26)_(52129515531).jpg" }, // Luca Van Assche
  209860: { src: "/players/209860.jpg", credit: "Tensionado", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Buse_W-S_2026.jpg" }, // Ignacio Buse
  209920: { src: "/players/209920.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Collignon_RGQ23_(52944022815).jpg" }, // Raphael Collignon
  209950: { src: "/players/209950.jpg", credit: "Gordons203", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Arthur_Fils_at_EFG_Swiss_Open_Gstaad_2023_Pic_Gordon_Simmonds.jpg" }, // Arthur Fils
  209976: { src: "/players/209976.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Dino_Pri%C5%BEmi%C4%87_(2023_French_Open)_06_(cropped).jpg" }, // Dino Prizmic
  210097: { src: "/players/210097.jpg", credit: "si.robi", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Shelton_MCM23_(27)_(52883150181).jpg" }, // Ben Shelton
  210150: { src: "/players/210150.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Jakub_Men%C5%A1%C3%ADk_(2023_US_Open)_02_(cropped).jpg" }, // Jakub Mensik
  210319: { src: "/players/210319.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Ethan_Quinn_(2023_US_Open)_02_(cropped).jpg" }, // Ethan Quinn
  210506: { src: "/players/210506.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Alex_Michelsen_(2023_Cary_2)_01.jpg" }, // Alex Michelsen
  210530: { src: "/players/210530.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Learner_Tien_(2024_US_Open)_04.jpg" }, // Learner Tien
  211663: { src: "/players/211663.jpg", credit: "Hameltion", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Jo%C3%A3o_Fonseca_(2024_Cary)_09_(cropped).jpg" }, // Joao Fonseca
  212588: { src: "/players/212588.jpg", credit: "Crosscourt View", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Rafael_J%C3%B3dar_Roland_Garros_2026_(cropped).jpg" }, // Rafael Jodar
};

export function playerPhoto(id: number): PlayerPhoto | null {
  return PLAYER_PHOTOS[id] ?? null;
}

/** Fallback monogram for players with no freely licensed photograph. */
export function initials(fullName: string): string {
  const parts = fullName.trim().split(/\s+/);
  if (parts.length === 0) return "?";
  const first = parts[0][0] ?? "";
  const last = parts.length > 1 ? parts[parts.length - 1][0] ?? "" : "";
  return (first + last).toUpperCase();
}
